### ISSUE TITLE
Deleting Items From Cart Issues

### ISSUE THREAD

**Issue by MatthewKennedy** [spree-contrib/spree_mailchimp_ecommerce#44]
When removing items from cart job fails in Sidekiq and goes into retires with message:
 
<img width="1194" alt="Screenshot 2019-07-08 at 11 12 50" src="https://user-images.githubusercontent.com/1240766/60802689-663a8b80-a171-11e9-822a-4e1e85a947c5.png">

I'm not sure if the line item was actually deleted in Mailchimp line items as the error is an ActiveRecord type not a Gibbon::MailChimpError.

**Comment by chhlga** [comment]
Fixed.
